### ISSUE TITLE
spm_encode not found

### ISSUE THREAD

**Issue by sandeep2244** [AI4Bharat/IndicTrans2#10]
Hey, 

I did clone and ran model with input text and expecting ouput in english, I downloaded model on my local mac m2 pro 

Getting below error
**joint_translate.sh: line 48: spm_encode: command not found**

Command i ran is below 
**bash joint_translate.sh input op hin_Deva eng_Latn ../../../Downloads/indic-en-deploy/fairseq_model**

Can you please help me to how i can export spm_encode 

I exported it with SPM_PATH but no chance.

**Comment by PranjalChitale** [comment]
https://github.com/AI4Bharat/IndicTrans2/blob/main/install.sh#L46

As mentioned in install.sh, in order to use spm_encode from the command line, you need to build the cpp binaries from the source repo.

Please refer to the sentencepiece github repository [link](https://github.com/google/sentencepiece#build-and-install-sentencepiece-command-line-tools-from-c-source) and follow the steps there, post this is done, the above issue should be resolved.

**Comment by sandeep2244** [comment]
@PranjalChitale , Thank you for the quick response, Issue resolved. 

It's running successful with no error. 

<img width="1440" alt="image" src="https://github.com/AI4Bharat/IndicTrans2/assets/28102791/66506e5c-2da3-4cb7-bd22-3ff0eec08f5e">

Now checking output.txt file is blank file with same number of blank lines as a input number of line.

Hindi to English AND English to English also get output blank. 

I see output.txt.log has below errors 

```
  File "/opt/homebrew/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1127, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

````
May be due to above errors log , it's not translating.

**Comment by PranjalChitale** [comment]
@sandeep2244 

https://github.com/facebookresearch/fairseq/issues/5012

^ Please create a new environment with Python 3.9 and this should be resolved.
