### ISSUE TITLE
Require Information For BPCC DataSheet

### ISSUE THREAD

**Issue by sofia100** [AI4Bharat/IndicTrans2#102]
Hi there,
For my academic project of Datasheet for BPCC dataset, it will be really helpful if you can check and rectify the below answers:

1. Is there an erratum? If so, please provide a link or other access point.
 (a) No specified erratum is available
2. Is there a repository that links to any or all papers or systems that use the dataset? If so, please provide a link or other access point.
(a) No, there is no link to the repository that maintains any or all papers or systems
that use the BPCC dataset.
3. Was the “raw” data saved in addition to the preprocessed/cleaned/labeled data (e.g., to support unanticipated future uses)? If so, please provide a link or other access point to the “raw” data.
(a) No such ”raw” data was saved.
4. Has an analysis of the potential impact of the dataset and its use on data subjects been conducted? If so, please provide a description of this analysis, including the outcomes, as well as a link or other access point to any supporting documentation.
(a) No rigorous experiment was conducted to analyze the potential impact of the BPCC dataset.
5. Were the individuals in question notified about the data collection? If so, please describe how notice was provided, and provide a link or other access point to, or otherwise reproduce, the exact language of the notification itself.
(a) No individuals were contacted for data collection.
6. Were any ethical review processes conducted (e.g., by an institutional review board)? If so, please provide a description of these review processes, including the outcomes, as well as a link or other access point to any supporting documentation.
(a) No ethical review process is mentioned.
7.  how were crowdworkers paid? How was the team compensated?
(a) Remuneration and compensation details are not mentioned 
8. If the dataset is a sample from a larger set, what was the sampling strategy (e.g., deterministic, probabilistic with specific sampling probabilities)?
(a) No sampling strategy is used to form subsets.
9. Will the dataset be updated (e.g., to correct labeling errors, add new instances, delete
instances)? If so, please describe how often, by whom.
(a) No mention about data updates but can be contacted at GitHub.
10. Will older versions of the dataset continue to be supported/hosted/maintained? If so, please describe how. If not, please describe how its obsolescence will be communicated to dataset consumers.
(a) Any obsolescence will be communicated by the GitHub repository. No mention about the maintainance of older versions.
11. If others want to extend/augment/build on/contribute to the dataset, is there a mechanism for them to do so? If so, please provide a description. Will these contributions be validated/verified? If so, please describe how. If not, why not? Is there a process for
communicating/distributing these contributions to dataset consumers? If so, please provide a description.
(a) No mention about addition of new data instances by external entities. This can affect the non-toxicity of the data if the external contributions are not adequately controlled.
12. Does the dataset have a digital object identifier (DOI)?
(a) DOI for dataset doesn't exsist
13. Have any third parties imposed IP-based or other restrictions on the data associated with the instances?
(a) No such restrictions have been imposed

Thank you for the cooperation.

**Comment by jaygala24** [comment]
Hi @sofia100 

Thanks for reaching out. I would recommend reading Section 4 and Appendix E from our [ArXiv version](https://arxiv.org/pdf/2305.16307v2). You should be able to find most of the details there.
