### ISSUE TITLE
Missing all_script_phonetic_data.csv File

### ISSUE THREAD

**Issue by sasidhar791** [AI4Bharat/IndicTrans2#104]
Hey @PranjalChitale ,

Thank you for the great work on IndicTrans2. While setting up the project, I encountered an issue regarding the `all_script_phonetic_data.csv` file. It appears to be required for the `scripts/add_joint_tags_translate.py` script and other parts of the pipeline, but I could not find it in the repository or accompanying documentation.

Could you please clarify the following:
1. Is this file available publicly? If yes, could you provide its location?
2. If not, how can it be generated or obtained?

Thank you for your guidance!

Best regards,  
Sasidhar Tade.

**Comment by PranjalChitale** [comment]
Hi @sasidhar791 

As described in the [install.sh](https://github.com/AI4Bharat/IndicTrans2/blob/main/install.sh#L27C1-L28C58) script, you need to clone the [indic_nlp_resources repository](https://github.com/anoopkunchukuttan/indic_nlp_resources) and then set the environment variable `INDIC_RESOURCES_PATH=<path>` to the path where you have cloned it.

This would resolve the above issue.

**Comment by sasidhar791** [comment]
Thank you. I'm able to access the all_script_phonetic_data.csv file now.
