### ISSUE TITLE
Not able to run hugging_interface -> example.py

### ISSUE THREAD

**Issue by ShimantaBhuyan** [AI4Bharat/IndicTrans2#107]
I followed the instructions in the Readme and tried running the example.py file, but got this error:
```
$ python3 example.py 
Traceback (most recent call last):
  File "/Users/devkrishna/Desktop/Playground/indic-language-stuff/indic-trans-2/IndicTrans2/huggingface_interface/example.py", line 176, in <module>
    en_indic_tokenizer, en_indic_model = initialize_model_and_tokenizer(
  File "/Users/devkrishna/Desktop/Playground/indic-language-stuff/indic-trans-2/IndicTrans2/huggingface_interface/example.py", line 105, in initialize_model_and_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(ckpt_dir, trust_remote_code=True)
  File "/Users/devkrishna/miniconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 906, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/Users/devkrishna/miniconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2032, in from_pretrained
    return cls._from_pretrained(
  File "/Users/devkrishna/miniconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2272, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/devkrishna/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2-en-indic-1B/bb1e8f494be5855fa00cf845bae310dc4f22a20e/tokenization_indictrans.py", line 97, in __init__
    raise KeyError("<unk> token must be in vocab")
```

I am running on macOS using miniconda.

**Comment by PranjalChitale** [comment]
We attempted to replicate the issue on our end by setting up a fresh environment and observed that example.py runs without any problems.

I would recommend you to double-check your setup.

You can use the [install.sh](https://github.com/AI4Bharat/IndicTrans2/blob/main/huggingface_interface/install.sh) script to ensure that the recommended versions of all dependencies are appropriately installed.

**Comment by ShimantaBhuyan** [comment]
I didn't run the 2nd step in the readme, because I didn't understand what the `checkpoint_best.pt` should be. I assumed it is meant for when we are using our finetuned model checkpoints. Is my assumption wrong? Where do I get this checkpoint if this step is necessary?

### Converting

In order to convert the fairseq checkpoint to a PyTorch checkpoint that is compatible with HuggingFace Transformers, use the following command:

```bash
python3 convert_indictrans_checkpoint_to_pytorch.py --fairseq_path <fairseq_checkpoint_best.pt> --pytorch_dump_folder_path <hf_output_dir>
```

- `<fairseq_checkpoint_best.pt>`: path to the fairseq `checkpoint_best.pt` that needs to be converted to HF compatible models
- `<hf_output_dir>`: path to the output directory where the HF compatible models will be saved

**Comment by ShimantaBhuyan** [comment]
> You can use the [install.sh](https://github.com/AI4Bharat/IndicTrans2/blob/main/huggingface_interface/install.sh) script to ensure that the recommended versions of all dependencies are appropriately installed.

I had run the `source install.sh` command as per the readme, but mosestokenizer, nltk and protobuf didn't get installed; which I had to then manually pip install later.

**Comment by PranjalChitale** [comment]
https://github.com/AI4Bharat/IndicTrans2/issues/107#issuecomment-2543858369

The conversion process is not necessary if you plan to use the pre-trained models directly.

The "Conversion" section in the README provides instructions on how to convert your own Fairseq models into HuggingFace format. The "best checkpoint path" refers to the location of your trained Fairseq model.

If your goal is simply to run inference with the pre-trained models, you can skip the Conversion section and instead follow the instructions in the "Inference" section of the README.

You can additionally check out this [Colab notebook](https://colab.research.google.com/github/AI4Bharat/IndicTrans2/blob/main/huggingface_interface/colab_inference.ipynb), which includes the same code as the example. 

We've tested it, and it works as expected.

**Comment by tap222** [comment]
Same error I am facing too, are you able to solve the issue

**Comment by tap222** [comment]
ile ~/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2-en-indic-1B/bb1e8f494be5855fa00cf845bae310dc4f22a20e/tokenization_indictrans.py:97, in IndicTransTokenizer.__init__(self, src_vocab_fp, tgt_vocab_fp, src_spm_fp, tgt_spm_fp, unk_token, bos_token, eos_token, pad_token, do_lower_case, **kwargs)
     95 self.encoder = self._load_json(self.src_vocab_fp)
     96 if self.unk_token not in self.encoder:
---> 97     raise KeyError("<unk> token must be in vocab")
     98 assert self.pad_token in self.encoder
     99 self.encoder_rev = {v: k for k, v in self.encoder.items()}

KeyError: '<unk> token must be in vocab'

**Comment by ShimantaBhuyan** [comment]
> Same error I am facing too, are you able to solve the issue

Unfortunately no, doesn't seem to work. I keep getting a similar error as you're facing
```
KeyError("<unk> token must be in vocab")
```

**Comment by tap222** [comment]
I have run the google colab same error I have faced

> [#107 (comment)](https://github.com/AI4Bharat/IndicTrans2/issues/107#issuecomment-2543858369)
> 
> The conversion process is not necessary if you plan to use the pre-trained models directly.
> 
> The "Conversion" section in the README provides instructions on how to convert your own Fairseq models into HuggingFace format. The "best checkpoint path" refers to the location of your trained Fairseq model.
> 
> If your goal is simply to run inference with the pre-trained models, you can skip the Conversion section and instead follow the instructions in the "Inference" section of the README.
> 
> You can additionally check out this [Colab notebook](https://colab.research.google.com/github/AI4Bharat/IndicTrans2/blob/main/huggingface_interface/colab_inference.ipynb), which includes the same code as the example.
> 
> We've tested it, and it works as expected.

Just now I have run the google colab notebook same error

**Comment by PranjalChitale** [comment]
The issue may have been caused by changes in the Transformers library, leading to a type mismatch in how special tokens were handled in the latest versions.

The issue has been resolved and you should be able to run inference now.

**Comment by tap222** [comment]
> The issue may have been caused by changes in the Transformers library, leading to a type mismatch in how special tokens were handled in the latest versions.
> 
> The issue has been resolved and you should be able to run inference now.

if feasible can you please let us know what went wrong that would be really helpful.

**Comment by PranjalChitale** [comment]
Refer this [commit](https://huggingface.co/ai4bharat/indictrans2-indic-en-dist-200M/commit/fedc1e170e01cd73e9ac95c7bc94a5182067ca77)

**Comment by tap222** [comment]
Thanks a lot it is working now.
