### ISSUE TITLE
How to combine data from different sources for training 

### ISSUE THREAD

**Issue by look4pritam** [AI4Bharat/IndicTrans2#17]
Thank you for wonderful work.

I am trying to reproduce the results.
I am having one query.

How to combine data from different sources for training ?

I am not able to find script for it.

**Comment by PranjalChitale** [comment]
You can use the following [script](https://github.com/AI4Bharat/IndicTrans2/blob/main/scripts/merge_bpcc.py) to merge and dedup data from different subsets of BPCC.

**Comment by look4pritam** [comment]
Thank you very much for quick reply.
I am trying to reproduce the results. 
I have found some documentation errors in training the models.
If interested, I can generate the merge request with correction.
