### ISSUE TITLE
file path of fairseq 

### ISSUE THREAD

**Issue by raut7218** [AI4Bharat/IndicTrans2#21]
python3 convert_indictrans_checkpoint_to_pytorch.py --fairseq_path <fairseq_checkpoint_best.pt> --pytorch_dump_folder_path <hf_output_dir>

which file path to insert between fairseq_checkpoint_best.pt and hf_output_dir
can yo please mention the file path or where i can find it

**Comment by PranjalChitale** [comment]
You can download the IndicTrans2 model checkpoints from [here](https://github.com/AI4Bharat/IndicTrans2#multilingual-translation-models) and unzip the same.

Inside the extracted folder, you will find a subfolder called `"fairseq_model"` Within this subfolder, there is a directory named `model`, which would contains a file named `checkpoint_best.pt`. This is the IndicTrans2 fairseq checkpoint which you intend to port into HF. (Alternatively if you are trying to convert your own fairseq model, pass the path to your fairseq checkpoint which you intend to port into HF).

Therefore, you should specify the path to the fairseq checkpoint, that needs to be ported into HF as the value for the "--fairseq_path" argument. The "--pytorch_dump_folder_path" argument is used to specify the path to the directory where you intend to store the HF ported model.
