### ISSUE TITLE
Speeding up Performance 

### ISSUE THREAD

**Issue by hemangsrr** [AI4Bharat/IndicTrans2#22]
I am running the translation engine on an ec2 instance, which has 8 T4 GPUs of 16GB VRAM each
Out of the total 128GB, the system seems to only be using about 3-6 constantly

Is there any way I can get this to use more of the GPU power and be faster?
Any specific parameters that might help me?

I can share the code segments or any other details if needed

**Comment by PranjalChitale** [comment]
1. This inference is running on a single GPU, while the rest of the GPUs you have remain unutilized.
2. Also, the GPU utilization of a single GPU which is in use is also not optimal, consider increasing the batch size to ensure optimal GPU usage.
3. If you have 8 GPUs, one option can be to divide the data you have into 8 shards and parallelize the inference by launching the inference on each GPU by specifying CUDA_VISIBLE_DEVICES=<gpu_id>, it would parallelize the process and improve your utilization. You can then aggregate the data.
4. You can also consider using the HuggingFace inference, along with 4bit / 8bit quantization (refer [example.py](https://github.com/AI4Bharat/IndicTrans2/blob/main/huggingface_inference/example.py)) which would have better throughput. 
5. With HF accelerate multi-GPU inference is also possible.

**Comment by hemangsrr** [comment]
I implemented the suggestions, and just a few comments on those, as well as a few questions

1. We have split up the input to multiple parts and are running one on each gpu, so that we have parallel processing
2. We have experimented with the Batch Size, and 8-10 seems optimal for us without risking CUDA going out of memory

It is with Quantization that we are facing troubles,

For Benchmarking, we have a curated Base file of about 50kb
On an Unquantized model, with all the tensors on CUDA, on a single GPU, this is taking around 4 minutes to process
While adding quantization, it seems to increase the inference time,
4 bit is taking close to 7 minutes, and 8 bit is taking about 10 minutes to process the same file

```
EnglishToIndicCheckpointDirectory = "ai4bharat/indictrans2-en-indic-1B"

BATCH_SIZE = 8
DEVICE = "cuda:0"

quantization_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_use_double_quant=True, bnb_4bit_compute_dtype=torch.bfloat16)

def InitializeModelAndTokenizer(CheckpointDirectory, Direction):

    Tokenizer = IndicTransTokenizer(direction=Direction)
    Model = AutoModelForSeq2SeqLM.from_pretrained(CheckpointDirectory, trust_remote_code=True,  device_map="auto", low_cpu_mem_usage=True, quantization_config=quantization_config)

    Model.eval()

    return Tokenizer, Model


def BatchTranslate(InputSentences, SourceLanguage, TargetLanguage, Model, Tokenizer):
    Translations = []
    for Index in range(0, len(InputSentences), BATCH_SIZE):
        Batch = InputSentences[Index : Index + BATCH_SIZE]

        # Preprocess the Batch and extract entity mappings
        Batch, EntityMap = preprocess_batch(
            Batch, src_lang=SourceLanguage, tgt_lang=TargetLanguage
        )

        # Tokenize the Batch and generate input Encodings
        Encodings = Tokenizer(
            Batch, src=True, truncation=True, padding="longest", return_tensors="pt", return_attention_mask=True
        )
        InputIDs, AttentionMask = Encodings["input_ids"].to(DEVICE), Encodings["attention_mask"].to(DEVICE)

        # Generate Translations using the Model
        GeneratedTokens = Model.generate(
            InputIDs,
            attention_mask=AttentionMask,
            num_return_sequences=1,
            num_beams=5,
            max_length=256,
            min_length=0,
        )

        # Decode the generated tokens into text
        GeneratedTokens = Tokenizer.batch_decode(
            GeneratedTokens.detach().tolist(), src=False
        )

        # Postprocess the Translations, including entity replacement
        Translations += postprocess_batch(
            GeneratedTokens, lang=TargetLanguage, placeholder_entity_map=EntityMap
        )

        del InputIDs, AttentionMask
        torch.cuda.empty_cache()

    return Translations



EnglishToIndicTokenizer, EnglishToIndicModel = InitializeModelAndTokenizer(
    EnglishToIndicCheckpointDirectory, "en-indic"
)
```

Above is the relevant portions of the code.

**Comment by harsha20032020** [comment]
@PranjalChitale can you share some scripts or resources to use hf autotrain in conjunction with hf_inferences?
I've been trying to parallelize inferences over multiple GPU's using hf autotrain but idk why, it just uses a single GPU at the end for batch inferences.

**Comment by jaygala24** [comment]
I suspect that the infer auto device map returns empty and potentially might be the reason. Please refer to the [huggingface forum](https://discuss.huggingface.co/t/infer-auto-device-map-returns-empty/24286/2) for further details.
