### ISSUE TITLE
Bug during Translation

### ISSUE THREAD

**Issue by saifulhaq8** [AI4Bharat/IndicTrans2#23]
IndicTrans2 hangs up while translating the following line:

"About $5 in the drugstore & the product will last for months.It doesn't hurt/burn or any of that jazz.--------------------------------------- Â\xad------."

I diagnosed the reason to be "--------------------------------------- Â\xad------."

Can we do something about this?

**Adding more details:** 

I did some experiments to find out the cause (note the full-stop):

1. "About $5 in the drugstore & the product will last for months.It doesn't hurt/burn or any of that jazz." gets successfully translated.
2. "--------------------------------------- Â\xad------." gets successfully translated.
3. ".--------------------------------------- Â\xad------" gets successfully translated.
4. ".--------------------------------------- Â\xad------." gets successfully translated.
5. "About $5 in the drugstore & the product will last for months.It doesn't hurt/burn or any of that jazz--------------------------------------- Â\xad------." gets successfully translated.
6. "About $5 in the drugstore & the product will last for months.It doesn't hurt/burn or any of that jazz.--------------------------------------- Â\xad------" hangs up.
7. "About $5 in the drugstore & the product will last for months.It doesn't hurt/burn or any of that jazz.--------------------------------------- Â\xad------." hangs up.

in the 5th experiment, i removed the full stop between "jazz" and "-".
in the 6th experiment, i removed the full-stop at the end of the line.

Hope this helps in resolving the bug.

**Comment by PranjalChitale** [comment]
Hi @saifulhaq8 this issue should be resolved now.
Thank you.

**Comment by saifulhaq8** [comment]
Thank you, the bug got resolved!
