### ISSUE TITLE
Transformers Integrations is not a package.

### ISSUE THREAD

**Issue by Gaurav0502** [AI4Bharat/IndicTrans2#25]
I was trying to use the HuggingFace inference for IndicTrans2. As guided in the <a href="https://github.com/AI4Bharat/IndicTrans2/tree/main/huggingface_inference">README file</a>, I executed the install.sh file and the setup was completed successfully. But, when I used the code from the example.py file, I encountered a ModuleNotFoundError for IndicTransTokenizer. 

After looking at <a href="https://github.com/AI4Bharat/indicTrans/issues/45">this issue</a>, I used "%cd IndicTrans2" and the previous ModuleNotFoundError was resolved but I got a new ModuleNotFoundError as given below:

ModuleNotFoundError: No module named 'transformers.integrations.deepspeed'; 'transformers.integrations' is not a package

I was executing everything in Kaggle.

How can this error be resolved?

**Comment by jaygala24** [comment]
Hey @Gaurav0502 

I think the issue might be due to some older transformers library version that you are using on Kaggle. Please try once with the `transformers>=4.33.2`.

**Comment by Gaurav0502** [comment]
Thanks @jaygala24, it worked for Kaggle.
