### ISSUE TITLE
Difference in inference scripts

### ISSUE THREAD

**Issue by jsk1808** [AI4Bharat/IndicTrans2#27]
I noticed that there are different scripts for inference:

1. /scripts/normalize_regex_inference.py
2. /inference/normalize_regex_inference.py

From the paper I understood that `<dnt>, </dnt>` tags are added to not translate the text in between, but the 2nd script seems to be handling this differently, by adding `<ID>`. Any reason for this?

**Comment by jaygala24** [comment]
Closing this matter due to lack of activity. Please feel free to reopen the issue if you have any questions or need further assistance.
