### ISSUE TITLE
Huggingface API example

### ISSUE THREAD

**Issue by okpatil4u** [AI4Bharat/IndicTrans2#28]
Could you please insert a Huggingface API example on the Readme.md and huggingface model card ? Current documentation and generation process is pretty obtuse. One could follow following standard template.

```
from transformers import MarianTokenizer, AutoModelForSeq2SeqLM

text = 'Рада познакомиться'
mname = 'Helsinki-NLP/opus-mt-ru-en'
tokenizer = MarianTokenizer.from_pretrained(mname)
model = AutoModelForSeq2SeqLM.from_pretrained(mname)
input_ids = tokenizer.encode(text, return_tensors="pt")
outputs = model.generate(input_ids)
decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(decoded) #Nice to meet you
```

Another way is creating a docker container where your research could be easily consumed.

**Comment by jaygala24** [comment]
Hi @okpatil4u 

We have already added scripts with documentation on how to use our HF compatible models in `IndicTrans2/huggingface_inference` subdirectory ([link](https://github.com/AI4Bharat/IndicTrans2/tree/main/huggingface_inference)). Thank you!

**Comment by okpatil4u** [comment]
I think you missed my comment. I had an intern go through the script. There were issues with specific python version and fairseq implementation. Rather than solving every issue reported by every user who is trying to access it, a simple huggingface API call or a docker container would be extremely helpful.

**Comment by okpatil4u** [comment]
For example, this is german to english model card on huggingface.

https://huggingface.co/kaitchup/Llama-2-7b-mt-German-to-English. Please check the uses section.

This is the industry standard for documentation nowadays.
