### ISSUE TITLE
HF model finetunning

### ISSUE THREAD

**Issue by Bhanu191** [AI4Bharat/IndicTrans2#37]
i am trying to finetune the HF model  ai4bharat/indictrans2-en-indic-dist-200M , i run the final command
"source train_lora.sh /content/en-indic-exp ai4bharat/indictrans2-en-indic-dist-200M en-indic eng_Latn hin_Deva /content/output"

but model is not saving in output dir (please check in ss) after completion of training.
could you please help here.
![Screenshot 2024-01-01 194205](https://github.com/AI4Bharat/IndicTrans2/assets/90096543/734936cc-791e-48db-acb4-590887b1589b)

Note: "bash train_lora.sh <data_dir> <model_name> <output_dir> <src_lang_list> <tgt_lang_list> "  
in above command  ,direction is  missing

**Comment by VarunGumma** [comment]
Thanks for pointing out the issue. The training scripts and `README` have been updated with the necessary information.
