### ISSUE TITLE
huggingface inference endpoint fails because of handler is not found

### ISSUE THREAD

**Issue by damodharanj** [AI4Bharat/IndicTrans2#40]
Hi team. I need help hosting the translation model inference alone. But the huggingface endpoint fails. 
Are there any instructions available for hosting the inference of ai4bharat models

<img width="882" alt="Screenshot 2024-01-11 at 4 39 10 PM" src="https://github.com/AI4Bharat/IndicTrans2/assets/8286067/e34d8642-0c1a-4ba1-b117-7a88f473db0c">

**Comment by jaygala24** [comment]
[IndicTransTokenizer](https://github.com/VarunGumma/IndicTransTokenizer) is currently not compatible with the `PreTrainedTokenizerBase` from the Huggingface transformers library. You will need an HF-compatible tokenizer to deploy the IndicTrans2 models on Huggingface Inference Endpoints. Instead, you can refer to [instructions](https://github.com/AI4Bharat/IndicTrans2/tree/main/inference/triton_server) on deploying IndicTrans2 models with the Fairseq interface using the Triton Server. Thanks!
