### ISSUE TITLE
Use of SPM models for Indic-Indic translation

### ISSUE THREAD

**Issue by allincowell** [AI4Bharat/IndicTrans2#43]
Hi Team,

I have a Prakrit-Hindi (Devanagiri script) dataset that I wanted to fine-tune one of the pre-trained Indictrans2 models. I am blocked on which SPM model to use as the only available options are En-Indic and Indic-En but my dataset is Indic-Indic.

Also, it seems like HuggingFace interface only allows Indictrans2 models for inference and not fine-tuning. Please clarify these two queries.

**Comment by PranjalChitale** [comment]
The SPM models and Fairseq dicts are already provided along with the checkpoints of the respective models. 

Please note that these get downloaded along with the respective checkpoint.

An additional download link has also been provided in the [readme](https://github.com/AI4Bharat/IndicTrans2?tab=readme-ov-file#using-our-spm-model-and-fairseq-dictionary).

Regarding HuggingFace interface, we support both inference and fine-tuning. 

Please check the HF Readme, where we provide instructions regarding the same. [LORA FT script](https://github.com/AI4Bharat/IndicTrans2/tree/main/huggingface_interface#fine-tuning-with-lora)
