### ISSUE TITLE
Using distilled indic-indic model for translation

### ISSUE THREAD

**Issue by allincowell** [AI4Bharat/IndicTrans2#44]
I am using the distilled pre-trained model checkpoint for indic-indic translation. I am getting error because of the --arch arguments which defaults to transformer_18_18.

Can you please tell which architecture to use? I am finetuning using our dataset.

**Comment by PranjalChitale** [comment]
For fine-tuning distilled models, you should use `transformer_base18L` arch,  as described in the [README](https://github.com/AI4Bharat/IndicTrans2?tab=readme-ov-file#training--fine-tuning).
