### ISSUE TITLE
 self._bin_buffer_mmap._mmap.close() AttributeError: 'MMapIndexedDataset' object has no attribute '_bin_buffer_mmap'

### ISSUE THREAD

**Issue by Sab8605** [AI4Bharat/IndicTrans2#45]
I have followed the all steps mention in the readme file and getting the below error while fine tuning.

Traceback (most recent call last):
  File "/home/translation-exp-vm/anaconda3/envs/itv2/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq_cli/train.py", line 528, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq_cli/train.py", line 131, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/tasks/translation.py", line 338, in load_dataset
    self.datasets[split] = load_langpair_dataset(
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/tasks/translation.py", line 85, in load_langpair_dataset
    src_dataset = data_utils.load_indexed_dataset(
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/data/data_utils.py", line 106, in load_indexed_dataset
    dataset = indexed_dataset.make_dataset(
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/data/indexed_dataset.py", line 86, in make_dataset
    return MMapIndexedDataset(path)
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/data/indexed_dataset.py", line 494, in __init__
    self._do_init(path)
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/data/indexed_dataset.py", line 507, in _do_init
    self._bin_buffer_mmap = np.memmap(
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/numpy/core/memmap.py", line 267, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: cannot mmap an empty file
Exception ignored in: <function MMapIndexedDataset.__del__ at 0x7f50e64aac10>
Traceback (most recent call last):
  File "/home/translation-exp-vm/anaconda3/envs/itv2/lib/python3.9/site-packages/fairseq/data/indexed_dataset.py", line 513, in __del__
    self._bin_buffer_mmap._mmap.close()
AttributeError: 'MMapIndexedDataset' object has no attribute '_bin_buffer_mmap'

I am just preparing the script for fine tuning by using sample data which is given in BPCC/daily dataset.

Thank you in advanced.

**Comment by PranjalChitale** [comment]
Please refer issue https://github.com/AI4Bharat/IndicTrans2/issues/26

**Comment by PranjalChitale** [comment]
Please provide some more details about your setup and the command you are using/

1. Have you used `install.sh` to setup your environment and ensured that all the dependencies are in place with the recommended versions installed. 
2. Can you paste the command you are using to fine-tune ?
3. Have you binarized the BPCC daily dataset using `prepare_data_joint_finetuning.sh` ?
4. Have you copied the final_bin directory provided along with the fairseq_model (pretrained checkpoint) to your experiment directory as mentioned in #26 ?

**Comment by Sab8605** [comment]
1.I have used install.sh to setup.

Versions I am using:
torch                     2.2.1+cu118            
torchaudio                2.2.1      
fairseq                   1.0.0a0+cf8ff8c

bash finetune.sh /home/translation-exp-vm/sab/IndicTrans2/exp transformer_base18  /home/translation-exp-vm/sab/data/jaygala/it2_ckpts/distilled_models/en-indic/fairseq_model/model

2.The above mention command I am using for fine tuning.
3.I also have binarized wiki dataset using command prepare_data_joint_finetuning.sh .
4. Also Copied the final_bin.

**Comment by Sab8605** [comment]
I am using the `transformer_base18L` this only the above is typo.
And using exact path of .pt file giving the same error.

**Comment by PranjalChitale** [comment]
> some files are creating but not having a single line in it. I am not getting why this files is empty and due to this showing the error.

Can you clarify which files are empty ?

**Comment by PranjalChitale** [comment]
> 3.I also have binarized wiki dataset using command prepare_data_joint_finetuning.sh .

`prepare_data_joint_finetuning.sh` expects that the training data is inside the train folder present inside the experiment directory.

Can you check if the dataset has properly binarized are not ?

Also please paste the contents of `preprocess.log` inside the `final_bin` folder inside your experiment directory.

That would help ascertain if your binarization was successful or not.

**Comment by Sab8605** [comment]
Yes the training data is inside the exp directory 
And the after binarizing it is in a same text format. so I think its not binarize correctly.
So can you help me with it.

**Comment by PranjalChitale** [comment]
Your data preprocessing has failed, which is why you get this error as observed in your logs.

> prepare_data_joint_finetuning.sh: line 92: parallel: command not found

Can you remove all the instances of `parallel --pipe --keep-order ` in `prepare_data_joint_finetuning.sh` and retry without using `parallel`.

Rerun `prepare_data_joint_finetuning.sh` and check if things are fine now.

**Comment by Sab8605** [comment]
After doing this 
errors starts with 
Normalizing punctuations for train
Applying do not translate tags for train
Traceback (most recent call last):
  File "/home/translation-exp-vm/sab/IndicTrans2/scripts/normalize_regex.py", line 94, in <module>
    num_lines = sum(1 for line in open(src_infname, "r"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/translation-exp-vm/sab/IndicTrans2/exp/norm/eng_Latn-gom_Deva/train.eng_Latn._norm'
Applying normalization and script conversion for train
Traceback (most recent call last):
  File "/home/translation-exp-vm/sab/IndicTrans2/scripts/preprocess_translate.py", line 164, in <module>
    print(preprocess(infname, outfname, lang, transliterate, remove_tag))
  File "/home/translation-exp-vm/sab/IndicTrans2/scripts/preprocess_translate.py", line 113, in preprocess
    num_lines = sum(1 for line in open(infname, "r"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/translation-exp-vm/sab/IndicTrans2/exp/norm/eng_Latn-gom_Deva/train.eng_Latn.norm'



and in the end the error is 

with open(filename, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/translation-exp-vm/sab/IndicTrans2/exp/final/train.SRC'

**Comment by PranjalChitale** [comment]
Just to confirm you removed only the highlighted part "parallel --pipe --keep-order" and not the entire line that had this ?

**Comment by Sab8605** [comment]
Yes after only removing "parallel --pipe --keep-order" that scripts work and get the results on terminal like below
Applying do not translate tags for dev
100%|█████████████████████████████████████████████████████████████████████████████████████| 997/997 [00:00<00:00, 11578.55it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 997/997 [00:00<00:00, 582899.51it/s]
Applying normalization and script conversion for dev
100%|█████████████████████████████████████████████████████████████████████████████████████| 997/997 [00:00<00:00, 10661.16it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████| 997/997 [00:00<00:00, 17688.28it/s]
Number of sentences in dev: 997
eng_Latn - hin_Deva
Normalizing punctuations for train
Applying do not translate tags for train
100%|█████████████████████████████████████████████████████████████████████████████████| 40270/40270 [00:02<00:00, 19484.52it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 40270/40270 [00:00<00:00, 682010.29it/s]
Applying normalization and script conversion for train
100%|█████████████████████████████████████████████████████████████████████████████████| 40270/40270 [00:01<00:00, 26737.65it/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 40270/40270 [00:00<00:00, 48682.95it/s]
Number of sentences in train: 40270

but when I checked the train folder the sentences still is in the same format and after running the finetuning script still getting the error
 self._bin_buffer_mmap._mmap.close()
AttributeError: 'MMapIndexedDataset' object has no attribute '_bin_buffer_mmap'


this is the changes I have did in finetune.sh
--distributed-world-size 1 \

**Comment by PranjalChitale** [comment]
Can you paste the `preprocess.log` inside the final_bin directory here.

**Comment by Sab8605** [comment]
Namespace(no_progress_bar=False, log_interval=100, log_format=None, log_file=None, tensorboard_logdir=None, wandb_project=None, azureml_logging=False, seed=1, cpu=False, tpu=False, bf16=False, memory_efficient_bf16=False, fp16=False, memory_efficient_fp16=False, fp16_no_flatten_grads=False, fp16_init_scale=128, fp16_scale_window=None, fp16_scale_tolerance=0.0, on_cpu_convert_precision=False, min_loss_scale=0.0001, threshold_loss_scale=None, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, user_dir=None, empty_cache_freq=0, all_gather_list_size=16384, model_parallel_size=1, quantization_config_path=None, profile=False, reset_logging=False, suppress_crashes=False, use_plasma_view=False, plasma_path='/tmp/plasma', criterion='cross_entropy', tokenizer=None, bpe=None, optimizer=None, lr_scheduler='fixed', scoring='bleu', task='translation', source_lang='SRC', target_lang='TGT', trainpref='/home/translation-exp-vm/sab/IndicTrans2/exp/final/train', validpref='/home/translation-exp-vm/sab/IndicTrans2/exp/final/dev', testpref=None, align_suffix=None, destdir='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin', thresholdtgt=0, thresholdsrc=0, tgtdict='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin/dict.TGT.txt', srcdict='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin/dict.SRC.txt', nwordstgt=-1, nwordssrc=-1, alignfile=None, dataset_impl='mmap', joined_dictionary=False, only_source=False, padding_factor=8, workers=4, dict_only=False)
[SRC] Dictionary: 32322 types
[SRC] /home/translation-exp-vm/sab/IndicTrans2/exp/final/train.SRC: 0 sents, 0 tokens (by <unk>)
[SRC] Dictionary: 32322 types
[SRC] /home/translation-exp-vm/sab/IndicTrans2/exp/final/dev.SRC: 0 sents, 0 tokens (by <unk>)
[TGT] Dictionary: 122672 types
[TGT] /home/translation-exp-vm/sab/IndicTrans2/exp/final/train.TGT: 0 sents, 0 tokens (by <unk>)
[TGT] Dictionary: 122672 types
[TGT] /home/translation-exp-vm/sab/IndicTrans2/exp/final/dev.TGT: 0 sents, 0 tokens (by <unk>)
Wrote preprocessed data to /home/translation-exp-vm/sab/IndicTrans2/exp/final_bin
Namespace(no_progress_bar=False, log_interval=100, log_format=None, log_file=None, tensorboard_logdir=None, wandb_project=None, azureml_logging=False, seed=1, cpu=False, tpu=False, bf16=False, memory_efficient_bf16=False, fp16=False, memory_efficient_fp16=False, fp16_no_flatten_grads=False, fp16_init_scale=128, fp16_scale_window=None, fp16_scale_tolerance=0.0, on_cpu_convert_precision=False, min_loss_scale=0.0001, threshold_loss_scale=None, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, user_dir=None, empty_cache_freq=0, all_gather_list_size=16384, model_parallel_size=1, quantization_config_path=None, profile=False, reset_logging=False, suppress_crashes=False, use_plasma_view=False, plasma_path='/tmp/plasma', criterion='cross_entropy', tokenizer=None, bpe=None, optimizer=None, lr_scheduler='fixed', scoring='bleu', task='translation', source_lang='SRC', target_lang='TGT', trainpref='/home/translation-exp-vm/sab/IndicTrans2/exp/final/train', validpref='/home/translation-exp-vm/sab/IndicTrans2/exp/final/dev', testpref=None, align_suffix=None, destdir='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin', thresholdtgt=0, thresholdsrc=0, tgtdict='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin/dict.TGT.txt', srcdict='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin/dict.SRC.txt', nwordstgt=-1, nwordssrc=-1, alignfile=None, dataset_impl='mmap', joined_dictionary=False, only_source=False, padding_factor=8, workers=4, dict_only=False)
[SRC] Dictionary: 32322 types
Namespace(no_progress_bar=False, log_interval=100, log_format=None, log_file=None, tensorboard_logdir=None, wandb_project=None, azureml_logging=False, seed=1, cpu=False, tpu=False, bf16=False, memory_efficient_bf16=False, fp16=False, memory_efficient_fp16=False, fp16_no_flatten_grads=False, fp16_init_scale=128, fp16_scale_window=None, fp16_scale_tolerance=0.0, on_cpu_convert_precision=False, min_loss_scale=0.0001, threshold_loss_scale=None, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, user_dir=None, empty_cache_freq=0, all_gather_list_size=16384, model_parallel_size=1, quantization_config_path=None, profile=False, reset_logging=False, suppress_crashes=False, use_plasma_view=False, plasma_path='/tmp/plasma', criterion='cross_entropy', tokenizer=None, bpe=None, optimizer=None, lr_scheduler='fixed', scoring='bleu', task='translation', source_lang='SRC', target_lang='TGT', trainpref='/home/translation-exp-vm/sab/IndicTrans2/exp/final/train', validpref='/home/translation-exp-vm/sab/IndicTrans2/exp/final/dev', testpref=None, align_suffix=None, destdir='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin', thresholdtgt=0, thresholdsrc=0, tgtdict='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin/dict.TGT.txt', srcdict='/home/translation-exp-vm/sab/IndicTrans2/exp/final_bin/dict.SRC.txt', nwordstgt=-1, nwordssrc=-1, alignfile=None, dataset_impl='mmap', joined_dictionary=False, only_source=False, padding_factor=8, workers=4, dict_only=False)
[SRC] Dictionary: 32322 types
[SRC] /home/translation-exp-vm/sab/IndicTrans2/exp/final/train.SRC: 0 sents, 0 tokens (by <unk>)
[SRC] Dictionary: 32322 types
[SRC] /home/translation-exp-vm/sab/IndicTrans2/exp/final/dev.SRC: 0 sents, 0 tokens (by <unk>)
[TGT] Dictionary: 122672 types
[TGT] /home/translation-exp-vm/sab/IndicTrans2/exp/final/train.TGT: 0 sents, 0 tokens (by <unk>)
[TGT] Dictionary: 122672 types
[TGT] /home/translation-exp-vm/sab/IndicTrans2/exp/final/dev.TGT: 0 sents, 0 tokens (by <unk>)
Wrote preprocessed data to /home/translation-exp-vm/sab/IndicTrans2/exp/final_bin

**Comment by PranjalChitale** [comment]
Have you placed the vocab directory provided with the checkpoint in your experiment directory ?

**Comment by Sab8605** [comment]
I have downloaded the SPM model and rename it vocab and pasted in the experiment folder as mentioned in Readme.md  file.

**Comment by PranjalChitale** [comment]
Please remove `parallel --pipe --keep-order` in  [apply_sentence_piece.sh](https://github.com/AI4Bharat/IndicTrans2/blob/main/apply_sentence_piece.sh)

**Comment by Sab8605** [comment]
Still not able to run the fine tuning script.
