### ISSUE TITLE
How to run IndicTrans2 using TPU's?

### ISSUE THREAD

**Issue by kathir-ks** [AI4Bharat/IndicTrans2#46]
Is it possible to run IndicTrans2 using google cloud tpus?

**Comment by jaygala24** [comment]
Hey @kathir-ks 

Our team has released the flax port for IndicTrans2 en-indic 200M distilled model in the [setu-translate](https://github.com/AI4Bharat/setu-translate/tree/528496176649196283388d79a62cc79a934564d3) repository. We will also be releasing the flax ports for the other models in the coming month. You can follow the instructions from the aforementioned repository for inference on TPUs. Thank you!

**Comment by kathir-ks** [comment]
Thank you
