### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by Manikantan-S** [AI4Bharat/IndicTrans2#51]
I read the paper of IndicTrans2 where i found some dataset benchmarks for indictrans2, can someone please provide me with the individual benchmark for each language of indictrans2 and what benchmarks are used for evaluation ,thank you

**Comment by jaygala24** [comment]
We would request you to please refer to the README for the details before opening any issues. We have already provided the links for [IN22 benchmark](https://github.com/AI4Bharat/IndicTrans2?tab=readme-ov-file#evaluation-data) in the IndicTrans2 README. Additionally, you can find the FLORES benchmark in the [FLORES GitHub repo](https://github.com/facebookresearch/flores/blob/main/flores200/README.md).
