### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by datha29** [AI4Bharat/IndicTrans2#52]
Hi Team

I am looking at fine tuning the model as per our used case.Would liike to know if meta data is required for fine tuning or not.Also whatt is the minimum number of pairs expected for fine tuning.And thirdly since I am looking at fine tuning the model across 12 Indian languages.Do we require translations for a given english text across all Indian languages

**Comment by prajdabre** [comment]
1. No meta data is required.
2. Depends on your use case. More pairs = Better
3. No

All this information is in the paper.
