### ISSUE TITLE
How to use this API for big Document translation? say about 1000 sentences in 1 go .

### ISSUE THREAD

**Issue by Laishram009** [AI4Bharat/IndicTrans2#58]
I want to use this API for bulk level translation, how can i do, it will be very helpful for my studies.

**Comment by jaygala24** [comment]
Please refer to our example.py script ([reference](https://github.com/AI4Bharat/IndicTrans2/blob/main/huggingface_interface/example.py)) that supports both batch translation of sentences and paragraph translation using our HF-compatible IndicTrans2 models. You can adjust the batch size as per your GPUs.
