### ISSUE TITLE
ctranslate related issue 

### ISSUE THREAD

**Issue by pr509** [AI4Bharat/IndicTrans2#59]
ct2-fairseq-converter --model_path model.pt --data_dir data-bin/ --output_dir ct2_model

in this what should i give in place of --data_dir can you plz explain me .

**Comment by PranjalChitale** [comment]
`--data_dir` Path to the the directory where in you have the respective fairseq dictionaries (final_bin directory).

**Comment by pr509** [comment]
thanks .
just one more thing i want confirm sir could we change the finetuned fairseq model in indictrans1 as ctranslate .is it possibe ?

**Comment by PranjalChitale** [comment]
Yes, it is possible to port fine-tuned variants of IndicTrans1 to CT2 as well, however the IndicTrans1 model has now been deprecated.

Therefore, we would encourage you to consider using / fine-tuning distilled variants of IndicTrans2 in case you are looking for a light-weight alternative, as IndicTrans2 distilled models have fewer parameters (~200M) than IndicTrans1 (~434M) and are superior to IndicTrans1 in terms of performance.

**Comment by pr509** [comment]
thanks for your help .
