### ISSUE TITLE
Indic-Indic translation models

### ISSUE THREAD

**Issue by santhoshtr** [AI4Bharat/IndicTrans2#6]
Hi, sorry if I missed this, under Multilingual Translation Models I see en-indic and indic-en models to download. If one want to translate between Indic languages, say Tamil to Hindi, is there indic-indic model? From the demo site I see that such translation is possible.

**Comment by PranjalChitale** [comment]
Hi, we currently use pivoting as a solution to serve Indic-Indic translation. In our hosted demo as well, we use the 2 models sequentially, given a source language sentence, we use the Indic-En model to generate an intermediate English output which is again forwarded to En-Indic model to serve the final translation. However, we do have plans to train and release M2M (Many-to-Many) model in the future (single model for all directions).
