### ISSUE TITLE
use with ctranslate 

### ISSUE THREAD

**Issue by pr509** [AI4Bharat/IndicTrans2#65]
when i am trying to convert trained fairseq model to ctranslate i got a source_vocabolary.json and target_vocabalory.json out of these two the target_vocab.json in full with unicodes and because of this the translation is not coming good .could you plz help me in finding solution for this

**Comment by PranjalChitale** [comment]
Post porting the fairseq model to ctranslate2, using the `ct2-fairseq-converter` the source and target vocabularies and dumped in txt format and not in json format, so this issue would never arise.

Can you share more details as to what was the command used ?
