### ISSUE TITLE
Issues for the Urdu and Kashmiri

### ISSUE THREAD

**Issue by Sab8605** [AI4Bharat/IndicTrans2#68]
Model gives error or empty string when translating the source language of Arabic script i.e. Urdu and Kashmiri in to any other  target language.

**Comment by PranjalChitale** [comment]
Can you please provide basic details like the model which you are using (base / distilled),  whether you are using Fairseq / HF models, also check if you have installed all the requisite dependencies.

**Comment by Sab8605** [comment]
I am using distilled model its working fine for english to indic but for endic to english  (Kasmiri and urdu) its returning empty line for one ward and when directly using indic to indic on triton server the above mention problem creating issue and thats why eng to indic model returns the error  **AssertionError: blank lines are not allowed** . Also tested on your demo site its giving empty line for one word for urdu and kashmiri to english.
