### ISSUE TITLE
Flash Attention on Mac

### ISSUE THREAD

**Issue by samayra2029** [AI4Bharat/IndicTrans2#69]
Due to Flash Attention not supported on Mac as Cuda support is deprecated, is there way to not tie with Flash Attention?

**Comment by PranjalChitale** [comment]
Fixed in https://github.com/AI4Bharat/IndicTrans2/commit/450b0b6cb768ed529d6b851a7b59f0b3eb778637.

**Comment by samayra2029** [comment]
Thanks It worked. !!
