### ISSUE TITLE
Unwanted model.TGT files in the CT2 release

### ISSUE THREAD

**Issue by santhoshtr** [AI4Bharat/IndicTrans2#7]
There are  a few files in CT2 release that is not required as far as I can see. 

* vocab/model.TGT
* vocab/vocab.SRC
* vocab/vocab.TGT

vocab/model.SRC works as sentencepiece model - for en->indic and indic->en. For detokenizing,[ just joining the items in output of translator is enough](https://github.com/wikimedia/mediawiki-services-machinetranslation/blob/master/translator/indictrans.py#L24). We got the translations working well with this setup for both en->indic and indic->en directions.

(Please let me know if I am mistaken in the usage of CT2 model. )

**Comment by PranjalChitale** [comment]
In the CT2 release, the files vocab/vocab.SRC and vocab/vocab.TGT are included but these are not necessary for the inference. These files are only provided for the purpose of understanding and inspecting the tokens present in the vocabulary.

The file vocab/model.SRC is essential for applying the SPM (SentencePiece) tokenization.

For detokenization, a simple approach is to concatenate the items in the output and replace the '▁' character with a space (' '). This method should work without the need for the vocab/model.TGT file, we just went with SPM decode for modularization purposes.

**Comment by santhoshtr** [comment]
Thanks. I was using SPM docode and noticed that it adds a significant time to the overall translation time. Removing it saved at least 25% of total translation in my tests.
