### ISSUE TITLE
Wrong translation for a Hindi Sentence using Indic-En Model

### ISSUE THREAD

**Issue by harshith-77** [AI4Bharat/IndicTrans2#88]
I am Encountering an issue when I try to translate the sentence "आप कैसे हैं?" from Hindi to English, it is being wrongly translated to "कैसा हैं?" when using Indic-En Model (ai4bharat/indictrans2-indic-en-1B). The below image is a screenshot of the output produced in the colab notebook you have provided in this repo.

![image](https://github.com/user-attachments/assets/f954d7a4-3e72-4c5b-9ea1-e2173093c4e8)

But when I am trying to translate the same sentence in https://ai4bharat.iitm.ac.in/resources/models/ website, expected output is being generated

![image](https://github.com/user-attachments/assets/99c61fa8-b69a-4c5c-80ef-ef0b36ec0db6)

The thing is that other than this sentence all the others are being translated correctly. What might be the reason causing this issue and what can I do to solve it?

**Comment by prajdabre** [comment]
What command did you use?

**Comment by harshith-77** [comment]
I have used the colab provided in this repo. I didn't change anything except the input sentence in Indic to English Example section as shown below.

![image](https://github.com/user-attachments/assets/fff5db26-922d-45c0-87d7-031e2a3035f1)

**Comment by prajdabre** [comment]
Hi

So I tested the notebook and believe it or not, I think "Aap kaise hai?" (In devanagari) Is a cursed example. Not sure why but this is the one example where the model fails. The moment you change it to "Raj Aap kaise hai?" And it works perfectly.

I don't think we can do anything about this. Alternatively can you try the distilled model once?

**Comment by tinku2603** [comment]
Yes, When we add some prefix to this sentence, it's translating perfectly.

**Comment by harshith-77** [comment]
Same issue with "आप कैसा है" and "तुम कैसे हो". Anyways I will try with distilled model as well.
