### ISSUE TITLE
Change in IndicTransTokenizer to IndicTransToolkit

### ISSUE THREAD

**Issue by sofia100** [AI4Bharat/IndicTrans2#96]
Hi there,
As per this update, https://github.com/VarunGumma/IndicTransToolkit?tab=readme-ov-file#minor-update-v102, tokenizer is changed. Can you please mention the changes needed for importing tokenizer?

**Comment by VarunGumma** [comment]
The tokenizer is now available in HF with the models. You can visit the [model page](https://huggingface.co/ai4bharat/indictrans2-indic-en-1B) for a detailed example on how to import the tokenizer from HF. More information also available in the [readme](https://github.com/VarunGumma/IndicTransToolkit) of IndicTransToolkit.
