### ISSUE TITLE
How to use IndicComet to evaluate IndicTrans2?

### ISSUE THREAD

**Issue by sofia100** [AI4Bharat/IndicTrans2#98]
As discussed in paper  [IndicMT Eval: A Dataset to Meta-Evaluate Machine Translation Metrics for Indian Languages](https://aclanthology.org/2023.acl-long.795.pdf), _ develop an Indic-COMET metric and show that it outperforms COMET counterparts in both human scores correlations and robustness scores in Indian languages._ 

How can I use this IndicComet model, in python, for evaluating various models?

On using the checkpoint URL, i'm getting the below error:
![image](https://github.com/user-attachments/assets/a3750217-1365-484f-a63a-be24279628f6)

Kindly assist. Thank you!

**Comment by PranjalChitale** [comment]
You'll need to download the checkpoints and the corresponding `hparams.yaml` file to your local machine using `wget` and provide the local path to the checkpoint to the `load_from_checkpoint` function.

You can find the links to the above resources in the [Indic-MT-Eval](https://github.com/AI4Bharat/IndicMT-Eval) repository.

You can also use the [compute_comet_score.sh](https://github.com/AI4Bharat/IndicTrans2/blob/main/compute_comet_score.sh) provided by us and pass the path to the checkpoint in your local directory as the `model_name` argument.
